### ISSUE TITLE
no releases for starter tutorial

### ISSUE THREAD

**Issue by knmcguire** [GodotVR/godot_openvr_fps#5]
Hi!

I'm following the VR tutorial but running in some problems. The docs for Godot version 3.2 in the VR tutorial mentions the following:
_If you have not already, go to the OpenVR GitHub repository (https://github.com/GodotVR/godot_openvr_fps (this repo)) and download the “Starter Assets” file from the releases_

However,  there are no releases on this repository and the starter files from  zip file from version 3.1 have bugs for godot version 3.2 so I can't use those.

**Comment by TwistedTwigleg** [comment]
My bad, I forgot to make the release. Thanks for letting us know! I'll make the release with the starter assets as soon as I can.

If you want/need, you can make the "Starter Assets" zip by downloading the finished project and deleting all the scripts.

**Comment by knmcguire** [comment]
Ah ok! No worries :) I'll wait

I tried your suggestion with the finished project. but unfortunately when I do that, I get all kinds of errors from the project due broken dependencies and such. I will just wait until the release.

**Comment by TwistedTwigleg** [comment]
I just published a release for Godot 3.2 stable that includes the starter assets. Thanks again for bringing this to our attention, and my apologizes for the incontinence.

Closing this issue...

If there is any other issues with the starter assets, please do not hesitate to let us know! We can always reopen this issue if needed.
